# .github/workflows/docs-widoco.yml

name: Docs (WIDOCO)
on:
  workflow_run:
    workflows: ["Ontology verification"]
    types: [completed]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  widoco:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: Airy59/OntoQA/.github/workflows/docs-widoco.yml@main
    with:
      main_ontology: ontology/src/core.ttl


# Note: gets triggered by "Ontology verification".
